// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCst114Bbg3O0lycKbMGn1ysuF5JoKIxFs',
    appId: '1:337635008288:android:11cbdbe80bf2b40c4a4145',
    messagingSenderId: '337635008288',
    projectId: 'hitches-mobile-app',
    storageBucket: 'hitches-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHdDMmIPjO1TJZdW2Y0VS6MLJcAzlXzc',
    appId: '1:337635008288:ios:5448e21705f55aac4a4145',
    messagingSenderId: '337635008288',
    projectId: 'hitches-mobile-app',
    storageBucket: 'hitches-mobile-app.appspot.com',
    androidClientId: '337635008288-5dngjvo6it8d8bb1au7hane0cq7a1ark.apps.googleusercontent.com',
    iosClientId: '337635008288-11di3fvpcnnac51il6e77c8mhejdsqa6.apps.googleusercontent.com',
    iosBundleId: 'com.zenmarkx.zenmark',
  );

}